system.debug( StringGenerator.randomString( new List<String>{'aa','bb','cc'} ) );

system.debug( StringGenerator.randomString( new List<String>{'aa','bb','cc'} ) );

system.debug( StringGenerator.randomString( new List<String>{'aa','bb','cc'} ) );

system.debug( StringGenerator.randomString( new List<String>{'aa','bb','cc'} ) );

system.debug( StringGenerator.randomString( new List<String>{'aa','bb','cc'} ) );

system.debug( StringGenerator.uniquelyRandomString( new List<String>{'aa','bb','cc'} ) );

system.debug( StringGenerator.uniquelyRandomString( new List<String>{'aa','bb','cc'} ) );

system.debug( StringGenerator.uniquelyRandomString( new List<String>{'aa','bb','cc'} ) );

system.debug( StringGenerator.listOfServedIndexes );

system.debug( StringGenerator.uniquelyRandomString( new List<String>{'aa','bb','cc'} ));

system.debug( StringGenerator.uniquelyRandomString( new List<String>{'aa','bb','cc'} ) );

system.debug( StringGenerator.uniquelyRandomString( new List<String>{'aa','bb','cc'} ) );

system.debug( StringGenerator.listOfServedIndexes );

system.debug( StringGenerator.uniquelyRandomString( new List<String>{'aa','bb','cc'} ) );

system.debug( StringGenerator.uniquelyRandomString( new List<String>{'aa','bb','cc'} ) );

system.debug( StringGenerator.uniquelyRandomString( new List<String>{'aa','bb','cc'} ) );

system.debug( StringGenerator.listOfServedIndexes );

system.debug( StringGenerator.uniquelyRandomString( new List<String>{'aa','bb','cc'} ) );



