System.debug( StringGenerator.randomString( new List<String>{'aa','bb','cc'} ) );

System.debug( StringGenerator.randomString( new List<String>{'aa','bb','cc'} ) );

System.debug( StringGenerator.randomString( new List<String>{'aa','bb','cc'} ) );

System.debug( StringGenerator.randomString( new List<String>{'aa','bb','cc'} ) );

System.debug( StringGenerator.randomString( new List<String>{'aa','bb','cc'} ) );

System.debug( StringGenerator.uniquelyRandomString( new List<String>{'aa','bb','cc'} ) );

System.debug( StringGenerator.uniquelyRandomString( new List<String>{'aa','bb','cc'} ) );

System.debug( StringGenerator.uniquelyRandomString( new List<String>{'aa','bb','cc'} ) );

System.debug( StringGenerator.uniquelyRandomString( new List<String>{'aa','bb','cc'} ));

System.debug( StringGenerator.uniquelyRandomString( new List<String>{'aa','bb','cc'} ) );

System.debug( StringGenerator.uniquelyRandomString( new List<String>{'aa','bb','cc'} ) );

System.debug( StringGenerator.uniquelyRandomString( new List<String>{'aa','bb','cc'} ) );

System.debug( StringGenerator.uniquelyRandomString( new List<String>{'aa','bb','cc'} ) );

System.debug( StringGenerator.uniquelyRandomString( new List<String>{'aa','bb','cc'} ) );

System.debug( StringGenerator.uniquelyRandomString( new List<String>{'aa','bb','cc'} ) );



